# Generated by Django 5.2.17 on 2026-08-09 17:14

import apps.registros.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=200)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('fecha_avistamiento', models.DateField(validators=[apps.registros.models.validar_fecha_no_futura])),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('DEVUELTO', 'Devuelto')], db_index=True, default='BORRADOR', max_length=20)),
                ('comportamiento', models.TextField(blank=True)),
                ('sustrato', models.CharField(blank=True, max_length=150)),
                ('info_adicional', models.TextField(blank=True)),
                ('sin_identificar', models.BooleanField(default=False)),
                ('especie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='catalogo.especie')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro',
                'verbose_name_plural': 'registros',
                'ordering': ['-fecha_avistamiento'],
            },
        ),
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to='registros/%Y/%m/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotografias', to='registros.registro')),
            ],
            options={
                'verbose_name': 'fotografía',
                'verbose_name_plural': 'fotografías',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
