# Generated by Django 5.2.17 on 2026-08-22 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioIdentificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=1000)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_identificacion', to='registros.registro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios_identificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'comentario de identificación',
                'verbose_name_plural': 'comentarios de identificación',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='VotoComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(choices=[('ME_GUSTA', 'Me gusta'), ('NO_ME_GUSTA', 'No me gusta')], max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='registros.comentarioidentificacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_comentarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'voto de comentario',
                'verbose_name_plural': 'votos de comentario',
                'constraints': [models.UniqueConstraint(fields=('comentario', 'usuario'), name='un_voto_por_usuario_y_comentario')],
            },
        ),
    ]
