# Generated by Django 5.2.17 on 2026-08-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_comentarioidentificacion_votocomentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='nombre_comun_agregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registro',
            name='nombre_comun_propuesto',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
