# Generated by Django 5.2.17 on 2026-08-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_registro_departamento_registro_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='hash_contenido',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
