# Generated by Django 5.2.17 on 2026-08-31 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_fotografia_hash_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='cantidad_individuos',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
