# Generated by Django 5.2.17 on 2026-08-31 23:40

import apps.registros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_registro_cantidad_individuos'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='codigos_reproductivos',
            field=models.JSONField(blank=True, default=list, validators=[apps.registros.models.validar_codigos_reproductivos]),
        ),
    ]
