# Generated by Django 5.2.17 on 2026-08-31 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    """codigos_reproductivos (lista) se reemplaza por codigo_reproductivo
    (un solo valor) en la migración 0008 — ver el porqué en
    apps/registros/codigos_reproductivos.py. El validador que citaba esta
    migración ya no existe en models.py; el campo que crea de todas formas
    se elimina en 0008, así que no hace falta reconstruirlo."""

    dependencies = [
        ('registros', '0006_registro_cantidad_individuos'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='codigos_reproductivos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
