# Generated by Django 5.2.17 on 2026-09-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_registro_codigos_reproductivos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='codigos_reproductivos',
        ),
        migrations.AddField(
            model_name='registro',
            name='codigo_reproductivo',
            field=models.CharField(blank=True, choices=[('NY', 'NY'), ('NE', 'NE'), ('FS', 'FS'), ('FY', 'FY'), ('CF', 'CF'), ('FL', 'FL'), ('ON', 'ON'), ('UN', 'UN'), ('DD', 'DD'), ('NB', 'NB'), ('CN', 'CN'), ('PE', 'PE'), ('B', 'B'), ('A', 'A'), ('N', 'N'), ('C', 'C'), ('T', 'T'), ('P', 'P'), ('M', 'M'), ('S7', 'S7'), ('S', 'S'), ('H', 'H'), ('F', 'F')], max_length=4),
        ),
    ]
