# Generated by Django 5.2.17 on 2026-08-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_solicitudrevisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='acepta_notificaciones_correo',
            field=models.BooleanField(default=False),
        ),
    ]
