# Generated by Django 5.2.17 on 2026-08-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cientifico', models.CharField(max_length=150, unique=True)),
                ('familia', models.CharField(blank=True, max_length=100)),
                ('orden', models.CharField(blank=True, max_length=100)),
                ('distribucion', models.TextField(blank=True)),
                ('tamano_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('historia_natural', models.TextField(blank=True)),
                ('dato_curioso', models.TextField(blank=True)),
                ('foto_referencia', models.ImageField(blank=True, null=True, upload_to='especies/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'especie',
                'verbose_name_plural': 'especies',
                'ordering': ['nombre_cientifico'],
            },
        ),
        migrations.CreateModel(
            name='NombreComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('es_local', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('APROBADO', 'Aprobado'), ('PROPUESTO', 'Propuesto')], default='APROBADO', max_length=20)),
            ],
            options={
                'verbose_name': 'nombre común',
                'verbose_name_plural': 'nombres comunes',
                'ordering': ['nombre'],
            },
        ),
    ]
