# Generated by Django 5.2.17 on 2026-08-09 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='especie',
            name='creado_por',
            field=models.ForeignKey(db_column='creado_por_id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='especies_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nombrecomun',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombres_comunes', to='catalogo.especie'),
        ),
        migrations.AddConstraint(
            model_name='nombrecomun',
            constraint=models.UniqueConstraint(fields=('especie', 'nombre'), name='nombre_comun_unico_por_especie'),
        ),
    ]
