# Generated by Django 5.2.17 on 2026-08-16 01:37

import apps.catalogo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especie',
            name='paises_distribucion',
            field=models.JSONField(blank=True, default=list, validators=[apps.catalogo.models.validar_paises_distribucion]),
        ),
    ]
