# Generated by Django 5.2.17 on 2026-09-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_especie_paises_distribucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='especie',
            name='categoria_amenaza',
            field=models.CharField(blank=True, choices=[('EX', 'Extinta'), ('EW', 'Extinta en estado silvestre'), ('CR', 'En peligro crítico'), ('EN', 'En peligro'), ('VU', 'Vulnerable'), ('NT', 'Casi amenazada'), ('LC', 'Preocupación menor'), ('DD', 'Datos insuficientes')], default='', max_length=2),
        ),
    ]
