# Generated by Django 5.2.17 on 2026-08-17 02:47

import apps.api_movil.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=apps.api_movil.models.generar_token, editable=False, max_length=64, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultimo_uso', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_acceso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'token de acceso móvil',
                'verbose_name_plural': 'tokens de acceso móvil',
            },
        ),
    ]
